//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurinaQnA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChatBot {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChatBot() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurinaQnA.Resources.ChatBot", typeof(ChatBot).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! My name is Loren and I&apos;m a Chatbot. I can help you with Animal&apos;s nurition related queries and locate products Retailer..
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you mean:.
        /// </summary>
        public static string answerSelectionPrompt {
            get {
                return ResourceManager.GetString("answerSelectionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Our Experts.
        /// </summary>
        public static string AskOurExperts {
            get {
                return ResourceManager.GetString("AskOurExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loren.
        /// </summary>
        public static string BotName {
            get {
                return ResourceManager.GetString("BotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve your query.
        /// </summary>
        public static string CannotResolveQuery {
            get {
                return ResourceManager.GetString("CannotResolveQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to get in touch with us, please click on the options below..
        /// </summary>
        public static string ContactUsOptionsMsg {
            get {
                return ResourceManager.GetString("ContactUsOptionsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our expert animal nutritionists and veterinarians are standing by to answer your toughest questions..
        /// </summary>
        public static string ContactUsSubTitle {
            get {
                return ResourceManager.GetString("ContactUsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the values, so that our expert can contact you.
        /// </summary>
        public static string ContactUsValidationTitle {
            get {
                return ResourceManager.GetString("ContactUsValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you &apos;{0}&apos;. Our experts will soon contact you on your email address: {1}..
        /// </summary>
        public static string ContactUsWithDetailsMsg {
            get {
                return ResourceManager.GetString("ContactUsWithDetailsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Retailers near to your location..
        /// </summary>
        public static string CouldNotFindRetailers {
            get {
                return ResourceManager.GetString("CouldNotFindRetailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe I didn&apos;t understand you properly. Could you please reword your question or type your complete query?.
        /// </summary>
        public static string CouldNotUnderstand {
            get {
                return ResourceManager.GetString("CouldNotUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found!.
        /// </summary>
        public static string defaultMessage {
            get {
                return ResourceManager.GetString("defaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Email address.
        /// </summary>
        public static string EmailAddressRequiredMessage {
            get {
                return ResourceManager.GetString("EmailAddressRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your query in relation to animal&apos;s nutrition.
        /// </summary>
        public static string FaqMessage {
            get {
                return ResourceManager.GetString("FaqMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to find more Retailers?.
        /// </summary>
        public static string FindMoreRetailers {
            get {
                return ResourceManager.GetString("FindMoreRetailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to find Retailers for any other location?.
        /// </summary>
        public static string FindRetailersForOtherLocation {
            get {
                return ResourceManager.GetString("FindRetailersForOtherLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bye. Looking forward to our next awesome conversation already..
        /// </summary>
        public static string GoodByeMessage {
            get {
                return ResourceManager.GetString("GoodByeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well hello there. What can I do for you today?.
        /// </summary>
        public static string GreetingsActionMessage {
            get {
                return ResourceManager.GetString("GreetingsActionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, how can i help you today?.
        /// </summary>
        public static string GreetingsMessage {
            get {
                return ResourceManager.GetString("GreetingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Name.
        /// </summary>
        public static string NameRequiredMessage {
            get {
                return ResourceManager.GetString("NameRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes, I may not have the information you need. I am a virtual assistant who can help you with information from the &lt;a href=&apos;https://www.purinamills.com/&apos; target=&apos;_blank&apos;&gt;Purina&apos;s&lt;/a&gt; website. .
        /// </summary>
        public static string NoMatchMessage {
            get {
                return ResourceManager.GetString("NoMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the above..
        /// </summary>
        public static string noneOfTheAboveOption {
            get {
                return ResourceManager.GetString("noneOfTheAboveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If I am not able to answer your questions, maybe our Experts will be more helpful..
        /// </summary>
        public static string NotHappyMessage {
            get {
                return ResourceManager.GetString("NotHappyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter ZipCode/City or State name to find Retailers.
        /// </summary>
        public static string RetailerFinderRequiredMessage {
            get {
                return ResourceManager.GetString("RetailerFinderRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure. Happy to help..
        /// </summary>
        public static string ThanksMessage {
            get {
                return ResourceManager.GetString("ThanksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string TitleFaq {
            get {
                return ResourceManager.GetString("TitleFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retailer Finder.
        /// </summary>
        public static string TitleRetailerFinder {
            get {
                return ResourceManager.GetString("TitleRetailerFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! Not able to match any of the options..
        /// </summary>
        public static string tooManyAttempts {
            get {
                return ResourceManager.GetString("tooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the list of top {0} nearest Retailers location....
        /// </summary>
        public static string TopNearestRetailersLocation {
            get {
                return ResourceManager.GetString("TopNearestRetailersLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi! My name is Loren and I&apos;m a Chatbot. I can help you with Animal&apos;s nurition related queries and locate products Retailer. Please select a quick link below or type your question in the space provided..
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks, what else I can help you with..
        /// </summary>
        public static string WhatElseHelp {
            get {
                return ResourceManager.GetString("WhatElseHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your question.
        /// </summary>
        public static string WhatIsQuestion {
            get {
                return ResourceManager.GetString("WhatIsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to know?.
        /// </summary>
        public static string WhatYouWouldLikeToKnow {
            get {
                return ResourceManager.GetString("WhatYouWouldLikeToKnow", resourceCulture);
            }
        }
    }
}
